export const ROUTES = {
  index: '/',
  auth: {
    signUp: '/auth/sign-up',
    signIn: '/auth/sign-in',
    changePassword: '/auth/change-password',
  },
  dashboard: '/dashboard',
  stations: '/stations',
  station: '/stations/:stationId',
  stationLocation: '/stations/:stationId/location',
  stationParameters: '/stations/:stationId/parameters',
  stationMeasurements: '/stations/:stationId/measurements',
  measurements: '/measurements',
  parameters: '/parameters',
  alarms: '/alarms',
  alerts: '/alerts',
  reports: '/reports',
  configuration: '/configuration',
  profile: '/profile',
  users: '/users',
  helpCenter: {
    index: '/help-center',
    dashboard: '/help-center/dashboard',
    stations: '/help-center/stations',
    parameters: '/help-center/parameters',
    notifications: '/help-center/notifications',
    alarms: '/help-center/alarms',
    alerts: '/help-center/alerts',
    users: '/help-center/users',
  },
}
