name: Production Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  production:
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: prod
    secrets: inherit
