name: Staging Deployment Workflow

on:
  pull_request:
    branches:
      - "**"

permissions:
  id-token: write
  contents: read

jobs:
  staging:
    uses: ./.github/workflows/deployment.yaml
    with:
      environment: dev
    secrets: inherit
